defaults:
  - _self_

num_epochs: 10
num_train_sample: 1
validation: true
kl_type: mean
entropy_type: conditional
dataset: cifar10
gamma: 1.0
lambda_info: 1.0
run_id: "gamma_${gamma}_lambda_${lambda_info}"
base_dir: ./hydra_experiments

hydra:
  run:
    dir: ${base_dir}/${run_id}
  sweep:
    dir: ${base_dir}
    subdir: ${run_id}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1
